mysite/myapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from myapp.views import hello,viewArticle,user,edit,update,show,destroy,task,show_task,update_task,destroy_task,edit_task,login
urlpatterns = [
    path('admin/', admin.site.urls),
    url('^hello/', hello, name='hello'),
    # url(r'^article/(\d+)/', 'viewArticle', name='article'),
    path('article/<int:articleId>/', viewArticle),
    path('article/<int:month>/<int:year>', viewArticle),
    path('admin/', admin.site.urls),
    path('user', user),
    path('show', show),
    path('edit/<int:id>', edit),
    path('update/<int:id>', update),
    path('delete/<int:id>', destroy),
    path('task', task),
    path('show_task', show_task),
    path('edit_task/<int:id>', edit_task),
    path('update_task/<int:id>', update_task),
    path('delete_task/<int:id>', destroy_task),
    path('login', login),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from myapp.views import hello

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
]

mysite/myapp/models.py
from django.db import models
from datetime import datetime
# Create your models here.
STATUS_CHOICES= [
    (0, 'Chưa hoàn thành'),
    (1, 'Hoàn thành'),
    ]
class Task(models.Model):

   Name = models.CharField(max_length = 50)
   Content = models.CharField(max_length = 50)
   StartTime = models.DateTimeField(default=datetime.now, blank=True)
   EndTime = models.DateTimeField(default=datetime.now, blank=True)
   CreatedDate = models.DateTimeField(default=datetime.now, blank=True)
   # Status = models.IntegerField()
   Status=models.IntegerField(choices=STATUS_CHOICES, default=0)
   UserId=models.ForeignKey('User', default = 1,on_delete=models.CASCADE,related_name='user_in_charge')
   CreatedUser = models.ForeignKey('User', default=1, on_delete=models.CASCADE,related_name='created_user')

   class Meta:
      db_table = "task"


class User(models.Model):
    Username = models.CharField(max_length=30)
    Password = models.CharField(max_length=30, default='')
    def __str__(self):
        return self.Username


class Meta:
    db_table = "user"

mysite/myapp/forms.py
from django import forms
from myapp.models import User,Task
from django.forms import formset_factory
from datetime import datetime
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = "__all__"
STATUS_CHOICES= [
    (0, 'Chưa hoàn thành'),
    (1, 'Hoàn thành'),
    ]
class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['id','Name','Content','StartTime','EndTime','CreatedDate','Status','UserId','CreatedUser']
        widgets = {'Status': forms.HiddenInput(),'CreatedUser': forms.HiddenInput()}

    def get_initial(self,User,Status):
        # call super if needed
        return {'CreatedUser': User,'Status':Status}


class LoginForm(forms.Form):
    user = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())


        # fields = "__all__"
# class TaskForm(forms.Form):
#     Name = forms.CharField(max_length=50)
#     Content = forms.CharField(max_length=50)
#     StartTime = forms.DateTimeField(initial=datetime.now())
#     EndTime = forms.DateTimeField(initial=datetime.now())
#     # Status = forms.IntegerField()
#     Status = forms.IntegerField(choices=STATUS_CHOICES, default=0)
    # UserId = forms.ForeignKey('User', default=1, on_delete=models.CASCADE)

mysite/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait

from myapp.models import Task
import datetime
from django.shortcuts import render, redirect
# Create your views here.
from myapp.forms import UserForm,TaskForm,LoginForm
from myapp.models import User,Task,STATUS_CHOICES
from selenium import webdriver
from selenium.webdriver.support.select import Select
from selenium.webdriver.support import expected_conditions as ec
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from django.contrib import messages
def user(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/myapp/show')
            except:
                pass
    else:
        form = UserForm()
    return render(request,'index.html',{'form':form})
def show(request):
    users = User.objects.all()
    return render(request,"show.html",{'users':users})
def edit(request, id):
    user = User.objects.get(id=id)
    return render(request,'edit.html', {'user':user})
def update(request, id):
    user = User.objects.get(id=id)
    form = UserForm(request.POST, instance = user)
    if form.is_valid():
        form.save()
        return redirect("/myapp/show")
    return render(request, 'edit.html', {'user': user})
def destroy(request, id):
    employee = User.objects.get(id=id)
    employee.delete()
    return redirect("/myapp/show")

def task(request):
    un = request.session['logUN'];
    usr = User.objects.get(Username=un)
    if request.method == "POST":

        form = TaskForm(request.POST,initial={'CreatedUser': usr})
        if form.is_valid():
            try:
                form.save()
                return redirect('/myapp/show_task')
            except Exception as ex:
                templ = "An exception of type {0} occurred. Arguments:\n{1!r}"
                message = templ.format(type(ex).__name__, ex.args)
                print (message)
    else:
        form = TaskForm(initial={'CreatedUser': usr})
    users = User.objects.all()
    return render(request,'index_task.html',{'form':form,'users':users})

def show_task(request):
    tasks = Task.objects.all()

    return render(request,"show_task.html",{'tasks':tasks})
def edit_task(request, id):
    task = Task.objects.get(id=id)
    users = User.objects.all()

    return render(request,'edit_task.html', {'task':task,"users":users})
def update_task(request, id):
    task = Task.objects.get(id=id)
    users = User.objects.all()
    if 'FinishTask' in request.POST:
        task.Status = 1
        task.save()
        return redirect("/myapp/show_task")
    form = TaskForm(request.POST, instance = task)

    if form.is_valid():
        form.save()
        return redirect("/myapp/show_task")
    return render(request, 'edit_task.html', {'task': task,"users":users})
def destroy_task(request, id):
    task = Task.objects.get(id=id)
    task.delete()
    return redirect("/myapp/show_task")


def login(request):
    username = "not logged in"

    if request.method == "POST":
        # Get the posted form
        form = LoginForm(request.POST)
        print(form.errors)
        if form.is_valid():
            username = form.cleaned_data['user']
            password = form.cleaned_data['password']
            try:
                user = User.objects.get(Username=form.cleaned_data['user'], Password=form.cleaned_data['password'])
            except Exception as e:
                messages.error(request, 'username or password not correct')
                return render(request, "login.html", {'form': form})
            request.session['logUN'] = form.cleaned_data['user']
            request.session['logPS'] = form.cleaned_data['password']
            return redirect("/myapp/show_task")

    else:
        form = LoginForm()

    return render(request, "login.html", {'form': form})




def hello(request):
   text = """<h1>welcome to my app !</h1>"""
   return HttpResponse(text)

def hello(request):
   today = datetime.datetime.now().date()
   daysOfWeek = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

   return render(request,'hello.html', {'today' : today,"days_of_week" : daysOfWeek})
def viewArticle(request, articleId):
   text = "Displaying article Number : %s"%articleId
   return HttpResponse(text)
def viewArticle(request, month, year):
   text = "Displaying articles of : %s/%s"%(year, month)
   return HttpResponse(text)

mysite/myapp/templates/Task/Index_task.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
        <div class="row">
    <div class="col-2 mx-3 my-4">
        <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Lưu</button>
      </form>
    </div>
</div>
{#<form method="POST" class="post-form" action="/myapp/task">#}
{#        {% csrf_token %}#}
{#    <div class="container">#}
{#<br>#}
{#    <div class="form-group row">#}
{#    <label class="col-sm-1 col-form-label"></label>#}
{#    <div class="col-sm-4">#}
{##}
{#    </div>#}
{#  </div>#}
{#    <div class="form-group row">#}
{#    <label class="col-sm-2 col-form-label">Id:</label>#}
{#    <div class="col-sm-4">#}
{#      {{ form.id }}#}
{#    </div>#}
{#  </div>#}
{#  <div class="form-group row">#}
{#    <label class="col-sm-2 col-form-label">Tiều đề:</label>#}
{#    <div class="col-sm-4">#}
{#      {{ form.Name }}#}
{#    </div>#}
{#  </div>#}
{#  <div class="form-group row">#}
{#    <label class="col-sm-2 col-form-label">Nội dung:</label>#}
{#    <div class="col-sm-4">#}
{#      {{ form.Content }}#}
{#    </div>#}
{#  </div>#}
{#  <div class="form-group row">#}
{#    <label class="col-sm-2 col-form-label">Bắt đầu:</label>#}
{#    <div class="col-sm-4">#}
{#      {{ form.StartTime }}#}
{#    </div>#}
{#  </div>#}
{#   <div class="form-group row">#}
{#    <label class="col-sm-2 col-form-label">Kết thúc:</label>#}
{#    <div class="col-sm-4">#}
{#      {{ form.EndTime }}#}
{#    </div>#}
{#  </div>#}
{#   <div class="form-group row">#}
{#    <label class="col-sm-2 col-form-label">Trạng thái:</label>#}
{#    <div class="col-sm-4 form-control">#}
{#      {{ form.Status }}#}
{#    </div>#}
{#  </div>#}
{##}
{#   <div class="form-group row">#}
{#    <label class="col-sm-2 col-form-label">Người thực hiện:</label>#}
{#    <div class="col-sm-4 form-control">#}
{#        <select name="UserId" id="id_UserId">#}
{#            {% for element in users %}#}
{#            <option value={{ element.id }}>{{ element.Username }}#}
{#             {% endfor %}#}
{#        </select>#}
{#    </div>#}
{#  </div>#}
{#    <div class="form-group row">#}
{#    <label class="col-sm-1 col-form-label"></label>#}
{#    <div class="col-sm-4 form-control">#}
{#    <button type="submit" class="btn btn-primary">Submit</button>#}
{#    </div>#}
{#  </div>#}
{#    </div>#}
{#</form>#}

{% endblock %}

mysite/myapp/templates/Task/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load staticfiles %}
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>
<body>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

mysite/myapp/templates/Task/edit_task.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-6 mx-3 my-4">
<form method="POST" class="post-form" action="/myapp/update_task/{{task.id}}">
        {% csrf_token %}
{% for field, errors in form.errors.items %}
    {% for error in errors %}
        <p>{{ error }}</p>
    {% endfor %}
{% endfor %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>

  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Id:</label>
    <div class="col-sm-4">
        <input type="text" name="id" id="id_id" required maxlength="20" value="{{ task.id }}" class="form-control"/>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Tiều đề:</label>
    <div class="col-sm-4">
        <input type="text" name="Name" id="id_Name" required maxlength="100" value="{{ task.Name}}" class="form-control"/>
    </div>
  </div>
   <div class="form-group row">
    <label class="col-sm-2 col-form-label">Nội dung:</label>
    <div class="col-sm-4">
        <input type="text" name="Content" id="id_Content" required maxlength="100" value="{{ task.Name}}" class="form-control"/>
    </div>
  </div>
   <div class="form-group row">
    <label class="col-sm-2 col-form-label">Bắt đầu:</label>
    <div class="col-sm-4">
        <input type="text" name="StartTime" id="id_StartTime" required maxlength="100" value="{{ task.StartTime|date:'Y-m-d H:i:s'}}" class="form-control"/>

    </div>
  </div>
   <div class="form-group row">
    <label class="col-sm-2 col-form-label">Kết thúc:</label>
    <div class="col-sm-4">
        <input type="text" name="EndTime" id="id_EndTime" required maxlength="100" value="{{ task.EndTime|date:'Y-m-d H:i:s'}}" class="form-control"/>
    </div>
    </div>
 <input type="hidden" name="Status" id="id_Status" required maxlength="100" value="{{ task.Status}}" class="form-control"/>
<input type="hidden" name="CreatedUser" id="id_CreatedUser" required maxlength="100" value="{{ task.CreatedUser.id}}" class="form-control"/>
         <div class="form-group row">
<label class="col-sm-2 col-form-label">Người thực hiện:</label>
<div class="col-sm-4">
    <select name="UserId" id="id_UserId" class="form-control">
        {% for element in users %}
            {% if task.UserId.id == element.id %}
        <option value={{ element.id }} selected>{{ element.Username }}
             {% else %}
                <option value={{ element.id }} >{{ element.Username }}
            {% endif %}
         {% endfor %}
    </select>
</div>
</div>


<div class="form-group row">
<label class="col-sm-1 col-form-label"></label>
<div class="col-sm-4">
<button type="submit" class="btn btn-success" name="UpdateTask">Cập nhật</button>
<button type="submit" class="btn btn-success" name="FinishTask">Hoàn thành</button>
</div>
</div>
</div>
 </div>
</form>
{#          <form method="post">#}
{#        {% csrf_token %}#}
{#        {{ form|crispy }}#}
{#        <button type="submit" class="btn btn-success">Lưu</button>#}
{#      </form>#}
    </div>
</div>

{% endblock %}

mysite/myapp/templates/Task/show_task.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>ID</th>
        <th>Tiêu đề</th>
        <th>Nội dung</th>
        <th>Bắt đầu</th>
        <th>Kết thúc</th>
             <th>Trạng thái</th>
         <th>Người làm</th>
          <th>Người tạo</th>
        <th>Thao tác</th>
    </tr>
    </thead>
    <tbody>
{% for task in tasks %}
    <tr>
        <td>{{ task.id }}</td>
        <td>{{ task.Name }}</td>
        <td>{{ task.Content }}</td>
        <td>{{ task.StartTime|date:'d/m/Y H:i:s'  }}</td>
        <td>{{ task.EndTime|date:'d/m/Y H:i:s' }}</td>
         <td>
          {% if task.Status == 0 %}
              <p>Đang thực hiện</p>
          {% else %}
              <p>Hoàn thành</p>
          {% endif %}
         </td>
        <td>{{ task.UserId.Username}}</td>
        <td>{{ task.CreatedUser.Username}}</td>
        <td>
            <a href="/myapp/edit_task/{{ task.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="/myapp/delete_task/{{ task.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/myapp/task" class="btn btn-primary">Thêm</a></center>
{% endblock %}

mysite/myapp/templates/User/Index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-2 mx-3 my-4">
        <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Lưu</button>
      </form>
    </div>
</div>

{% endblock %}

mysite/myapp/templates/User/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load staticfiles %}
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<style>
      <style>
    /* Stackoverflow preview fix, please ignore */
    .navbar-nav {
      flex-direction: row;
    }

    .nav-link {
      padding-right: .5rem !important;
      padding-left: .5rem !important;
    }

    /* Fixes dropdown menus placed on the right side */
    .ml-auto .dropdown-menu {
      left: auto !important;
      right: 0px;
    }
  </style>
</style>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-light">

  <!-- Links -->
  <ul class="navbar-nav">
                        <li class="nav-item">
      <a class="nav-link" href="/myapp/show">Users</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/myapp/show_task">Task</a>
    </li>
    <li class="nav-item">

    </li>
  </ul>
 <ul class="navbar-nav ml-auto">
    <li class="nav-item">
         {{ request.session.logUN }}
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/myapp/login">Đăng xuất</a>

    </li>

</ul>

</nav>
<div class="select2-container">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

mysite/myapp/templates/User/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-6 mx-3 my-4">
{#  <form method="post">#}
{#    {% csrf_token %}#}
{#    {{ form|crispy }}#}
{#    <button type="submit" class="btn btn-success">Save person</button>#}
{#  </form>#}
        <form method="POST" class="post-form" action="/myapp/update/{{user.id}}">
        {% csrf_token %}

    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Id:</label>
    <div class="col-sm-4">
        <input type="text" name="id" id="id_id" required maxlength="20" value="{{ user.id }}" class="form-control"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Username:</label>
    <div class="col-sm-4">
        <input type="text" name="Username" id="id_Username" required maxlength="100" value="{{ user.Username}}" class="form-control"/>
    </div>
  </div>
 <div class="form-group row">
    <label class="col-sm-2 col-form-label">Password:</label>
    <div class="col-sm-4">
        <input type="text" name="Password" id="id_Password" required maxlength="100" value="{{ user.password}}" class="form-control"/>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>

</form>
    </div>
</div>

{% endblock %}

mysite/myapp/templates/User/show.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>ID</th>
        <th>Name</th>

        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for user in users %}
    <tr>
        <td>{{ user.id }}</td>
        <td>{{ user.Username }}</td>
        <td>
            <a href="/myapp/edit/{{ user.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="/myapp/delete/{{ user.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/myapp/user" class="btn btn-primary">Add New Record</a></center>
{% endblock %}

mysite/myapp/templates/hello.html
{% extends "main_template.html" %}
{% block title %}My Hello Page{% endblock %}
{% block content %}

Hello World!!!<p>Today is {{today}}</p>
We are
{% if today.day == 1 %}

the first day of month.
{% elif today.day == 30 %}

the last day of month.
{% else %}

I don't know.
{%endif%}
<p>
    {%  for day in days_of_week %}
    {{ day }}
</p>
{% endfor %}
{% endblock %}

mysite/myapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load staticfiles %}
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>
<html>
   <body>
{#action = "{% url "myapp.views.login" %}"#}
      <form name = "form"
         method = "POST"  class="m-5">{% csrf_token %}

         <div style = "max-width:470px;">
            <center>
               <input type = "text" style = "margin-left:20%;"
                  placeholder = "Username" name = "user" class="form-control"/>
            </center>
         </div>

         <br>

         <div style = "max-width:470px;">
            <center>
               <input type = "password" style = "margin-left:20%;" class="form-control"
                  placeholder = "Password" name = "password" />
            </center>
         </div>
      <br>
        {% for message in messages %}
                <div class="alert alert-success text-danger">
                    <a class="close" href="#" data-dismiss="alert">×</a>
                    {{ message }}
                </div>
            {% endfor %}
         <br>

         <div style = "max-width:470px;">
            <center>

               <button style = "border:0px; background-color:#4285F4; margin-top:8%;
                  height:35px; width:80%;margin-left:19%;" type = "submit"
                  value = "Login" >
                  <strong>Login</strong>
               </button>

            </center>
         </div>

      </form>

   </body>
</html>

mysite/myapp/templates/main_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load staticfiles %}
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

mysite/mysite/templates/hello.html
<html>

   <body>
      Hello World!!!<p>Today is {{today}}</p>
   </body>

</html>